config/routes.rb
# frozen_string_literal: true

GizSolutions::Application.routes.draw do
  default_url_options host: GizSolutions.config.hostname

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  get 'download_pdf', to: "pages#download_pdf"

  get 'legal', to: 'pages#legal'

  resources :restore_solutions, only: :update

  resources :solutions do
    resource :winners, only: :update
  end

  namespace :admin do
    resource :export_solutions, only: :show
    resource :application_state, only: %i[edit update]
  end
end

app/models/application_state.rb
# frozen_string_literal: true

class ApplicationState < ApplicationRecord
  enum state: %i[collection judging announce_winners]

  def self.instance
    first || ApplicationState.create
  end
end

app/controllers/admin/application_states_controller.rb
# frozen_string_literal: true

class Admin::ApplicationStatesController < ApplicationController
  before_action :authenticate_admin!

  expose :winning_solutions, -> { Solution.winners }

  def edit
    render "edit_#{ApplicationState.instance.state}_state"
  end

  def update
    ApplicationState.instance.update(
      state: application_state_params[:state].to_i
    )
    redirect_to :edit_admin_application_state
  end

  private

  def application_state_params
    params.permit(:state)
  end
end

app/controllers/application_states_controller.rb
# frozen_string_literal: true

class ApplicationStatesController < ApplicationController
  before_action :authenticate_admin!

  expose :winning_solutions, -> { Solution.winners }

  def edit
    render "edit_#{ApplicationState.instance.state}_state"
  end

  def update
    ApplicationState.instance.update(
      state: application_state_params[:state].to_i
    )
    redirect_to :edit_application_state
  end

  private

  def application_state_params
    params.permit(:state)
  end
end

app/views/application_states/edit_collection_state.html.haml
.container
  .full_width
    %h3 Is it time to start judging the solution submissions?

    %p
      %span.bold Once this is executed user will no longer be able to submit more solutions.
      The option to submit will be hidden while you select three winners. You can revert this feature by clicking 'continue accepting submissions' after.

    = button_to I18n.t('buttons.judging'), application_state_path(state: ApplicationState.states['judging']), method: :put