config/routes.rb
# frozen_string_literal: true

GizSolutions::Application.routes.draw do
  default_url_options host: GizSolutions.config.hostname

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  get 'download_pdf', to: "pages#download_pdf"

  get 'legal', to: 'pages#legal'

  resources :restore_solutions, only: :update

  resources :solutions do
    resource :winners, only: :update
  end

  namespace :admin do
    resource :export_solutions, only: :show
    resource :application_state, only: %i[edit update]
  end
end

app/models/solution.rb
# frozen_string_literal: true

class Solution < ApplicationRecord
  acts_as_paranoid
  belongs_to :user

  validates :user, :hero_image, :title, :description, :business_opportunities,
            :implementation_impact, :skills_experience, presence: true

  validates :terms_accepted, inclusion: {
    in: [true], message: 'Terms must be accepted'
  }
  validates :licensing_accepted, inclusion: {
    in: [true], message: 'Licensing and copyright terms must be accepted'
  }

  has_attached_file :hero_image,
                    styles: { medium: '300x300>', thumb: '50x50>' },
                    default_url: ''

  validates_attachment_content_type :hero_image, content_type: %r{\Aimage\/.*\z}

  validates :hero_image, attachment_presence: true
  validates_with AttachmentPresenceValidator, attributes: :hero_image
  validates_with AttachmentSizeValidator, attributes: :hero_image, less_than: 5.megabytes

  scope :winners, -> { where(winner: true) }
end

app/controllers/solutions_controller.rb
# frozen_string_literal: true

class SolutionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :authenticate_admin!, only: :destroy
  before_action :authenticate_can_edit!, only: %i[update edit]

  before_action :authenticate_can_show_archived!, only: %i[show]
  before_action :set_cache_headers, only: %i[new]
  
  expose :solution, scope: :with_deleted

  expose :winning_solutions, -> { Solution.winners }
  expose :solutions, lambda {
    if ApplicationState.instance.announce_winners?
      Solution.where(winner: false)
    else
      Solution.all
    end
  }

  expose :deleted_solutions, lambda {
    Solution.only_deleted if admin_logged_in
  }

  expose :can_edit_solution, lambda {
    ApplicationState.instance.collection? &&
      (admin_logged_in || current_user&.solution == solution)
  }

  expose :solution_navigator, lambda {
    if current_user&.admin?
      SolutionNavigator.new(Solution.with_deleted.pluck(:id), params[:id].to_i)
    else
      SolutionNavigator.new(Solution.pluck(:id), params[:id].to_i)
    end
  }

  def show;  end

  def index; end

  def new
    if current_user.solution.nil?
      render :new
    else
      redirect_to edit_solution_path(current_user.solution)
    end
  end

  def destroy
    if solution.delete
      flash[:success] = 'The solution has been archived and no longer viewable by the public'
    else
      flash[:error] = "We're sorry, but something went wrong."
    end
    redirect_to solution_path(solution)
  end

  def create
    solution.user = current_user
    if solution.save
      SolutionMailer.notify_admins(
        User.admins.collect(&:email), solution
      ).deliver_now
      flash[:success] = 'Your solution has been created'
      redirect_to solution_path(solution)
    else
      render :new
    end
  end

  def edit; end

  def update
    if solution.update(solution_params)
      flash[:success] = 'Your changes have been saved'
      redirect_to solution_path(solution)
    else
      render :edit
    end
  end

  private
  
  def set_cache_headers
    response.headers['Cache-Control'] = 'no-cache, no-store'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
  end

  def authenticate_can_show_archived!
    return unless solution.deleted?
    return if admin_logged_in
    not_authorised
  end

  def authenticate_can_edit!
    return if can_edit_solution
    not_authorised
  end

  def solution_params
    params.require(:solution).permit(
      :title,
      :terms_accepted,
      :licensing_accepted,
      :description,
      :business_opportunities,
      :skills_experience,
      :implementation_impact,
      :embedded_video_url,
      :website,
      :hero_image
    )
  end
end

app/views/solutions/_admin_buttons.html.haml
- unless solution.winner?
  = button_to I18n.t('buttons.restore'), restore_solution_path(solution), class: "button", method: :put if solution.deleted?
  = button_to I18n.t('buttons.archive'), solution_path(solution), class: "button", method: :delete if solution.deleted_at.nil?

- if ApplicationState.instance.judging?
  = button_to I18n.t('buttons.deselect_winner'), solution_winners_path(solution), class: "button", method: :put, remote: true if solution.winner?
  = button_to I18n.t('buttons.select_winner'), solution_winners_path(solution), class: "button", method: :put, remote: true unless solution.winner?

.user_details
  -user = User.find(solution.user_id)
  %span.bold Contact details:
  %span=user.name
  %span=mail_to user.email

  %hr

app/views/solutions/_deleted_solution.html.haml
.single_solution.third.deleted
  =link_to solution_path(deleted_solution) do
    .solution_image
      = image_tag deleted_solution.hero_image.url(:medium)
    .solution_content
      =deleted_solution.title

app/views/solutions/_solution.html.haml
.single_solution.third
  =link_to solution_path(solution) do
    .solution_image
      = image_tag solution.hero_image.url, class: 'auto_fit_image'
    .solution_content
      =solution.title

app/views/solutions/_solution_fields.html.haml
= form.error_notification

-if solution.hero_image?
  %p Current banner image:
  =image_tag solution.hero_image, class: 'small_img'
  %br
  %br
  = form.input :hero_image, as: :file, label: 'Replace your banner image', hint: 'Choose a photo for your solution. Good photos will be at least 1024 pixels wide and 450 pixels tall, but no larger than 4MB.'
-else
  = form.input :hero_image, as: :file, label: 'Upload a banner image to describe your solution', hint: "Choose a photo for your solution to catch people's eyes. Good photos will be at least 1024 pixels wide and 450 pixels tall, but no larger than 5MB."

=form.input :description, as: :text, label: 'Describe your solution:', input_html: { maxlength: 500 }

=form.input :business_opportunities, as: :text, label: 'How does your solution strengthen business exchange between refugees and host communities?', input_html: { maxlength: 500 }

=form.input :implementation_impact, as: :text, label: "How has it been implemented? What's the impact of your solution?", input_html: { maxlength: 500 }

=form.input :skills_experience, as: :text, label: 'Tell us about your skills and experience useful for local communities on site:', input_html: { maxlength: 500 }

=form.input :title, as: :string, label: 'Choose a headline to summarise your solution:', input_html: { maxlength: 60 }

=form.input :website, as: :string, label: '(Optional) If there is a website with more details add here:'

.video_input
  %label Share a video too if you have one.
  .normal
    %p From your video on YouTube you need to:
    %ol.default
      %li Select the share button,
      %li Choose the Embed option,
      %li Copy the embed code that is in the text box and paste below.
    %p You can also embed Vimeo, Blip.tv, Viddler and Kickstarter videos in the same way

  =form.input :embedded_video_url, as: :text, label: false

-if form.object.new_record?
  = form.input :licensing_accepted, as: :boolean, required: true, label: "I accept GIZ's #{link_to('licensing & copyright terms', asset_path('giz_licensing_and_copyright.pdf'), target: '_blank')}.".html_safe
  = form.input :terms_accepted, as: :boolean, required: true, label: "I accept GIZ's #{link_to('Terms & Conditions', asset_path('giz_terms_conditions.pdf'), target: '_blank')} and #{link_to('Data protection policy', asset_path('giz_data_processing.pdf'), target: '_blank')}".html_safe

.form-actions.full_width_cta
  = form.submit t('buttons.save')

app/views/solutions/edit.html.haml
.container
  .full_width
    .thinner.full_width_inputs
      %h2=t('solution.edit')
      %p
        You can submit and edit your solution until the
        %span.bold 31.10.2018.
      %br
      = simple_form_for solution, url: solution_path(solution), method: :put do |form|
        =render partial: 'solution_fields', locals: { form: form }

app/views/solutions/index.html.haml
.container
  .full_width
    .thinner
      - if ApplicationState.instance.announce_winners?
        %h3=t('solution.winners.title')
        #all_solutions.inner_container
          = render partial: 'solutions/solution', collection: winning_solutions

      - if solutions.any?
        %h3= solutions_title
        #all_solutions.inner_container
          = render partial: 'solution', collection: solutions
      -else
        %h3=t('solution.all.none')
        .large_cta.full_width.center
          = link_to t('buttons.submit_solution'), current_user ? :new_solution : :new_user_registration, id: 'submit_nav'

          =link_to t('buttons.go_home'), :root, class: 'button secondary'

      - if deleted_solutions.present?
        %h3=t('solution.deleted.title')
        #all_solutions.inner_container
          = render partial: 'deleted_solution', collection: deleted_solutions

app/views/solutions/new.html.haml
.container
  .full_width
    .thinner.full_width_inputs.restricted_form
      %br
      %h2=t('solution.create')
      %p
        You can submit and edit your solution until the
        %span.bold 31.10.2018.
      %br

      = simple_form_for solution do |form|
        =render partial: 'solution_fields', locals: { form: form }

app/views/solutions/show.html.haml
#solution_show.container
  .full_width
    .thinner
      .solution_actions
        - if can_edit_solution
          = link_to 'edit', edit_solution_path(solution), class: 'button'
        - if admin_logged_in
          = render partial: 'admin_buttons'
      .solution_image
        = image_tag solution.hero_image.url

      %h1=solution.title
      %p="by #{solution.user.name}"
      -if solution.user.organisation
        ="from #{solution.user.organisation}"

      =link_to solution.website, solution.website, :target => "_blank"

      %hr

      %h2 Our solution
      %p=solution.description

      %hr

      %h2 What's the business opportunity for host and refugee community
      %p=solution.business_opportunities

      %hr

      %h2 How has it been implemented and what impact it had
      %p=solution.implementation_impact

      %hr

      %h2 Our Skills and Experience
      %p=solution.skills_experience


      - if solution.embedded_video_url
        .video_embed
          =solution.embedded_video_url.html_safe
      .nxt_btns
        .half
          -if solution_navigator.previous_solution_id
            =link_to solution_path(id: solution_navigator.previous_solution_id) do
              =fa_icon "caret-left"
              Previous solution
        .half.right
          -if solution_navigator.next_solution_id
            =link_to solution_path(id: solution_navigator.next_solution_id) do
              Next solution
              =fa_icon "caret-right"