config/routes.rb
# frozen_string_literal: true

GizSolutions::Application.routes.draw do
  default_url_options host: GizSolutions.config.hostname

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'pages#home'

  get 'download_pdf', to: "pages#download_pdf"

  get 'legal', to: 'pages#legal'

  resources :restore_solutions, only: :update

  resources :solutions do
    resource :winners, only: :update
  end

  namespace :admin do
    resource :export_solutions, only: :show
    resource :application_state, only: %i[edit update]
  end
end

app/views/layouts/_alerts.html.haml
- flash.each do |name, msg|
  - next unless msg.is_a?(String) && msg.present?
  #alerts
    .container
      .full_width
        = content_tag :div, msg, :id => "flash_#{name}"
        #alert_close
          =fa_icon "times"

app/views/layouts/_html_head.html.haml
%meta{charset: "utf-8"}
%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}

%meta{content: "yes", name: "apple-mobile-web-app-capable"}
%meta{content: "#000000", name: "theme-color"}


%meta{content: page_og_url, property: "og:url"}
%meta{content: "website", property: "og:type"}
%meta{content: 'GIZ Call for Solutions', property: "og:title"}
%meta{content: "What's your solution? Contribute your solutions to improve the lives of refugees. #solutionschallenge" , property: "og:description"}
%meta{content: "#{root_url}share_image.jpg", property: "og:image"}

%title GIZ Call for Solutions

= favicon_link_tag 'favicon.ico'

= stylesheet_link_tag    "application"
= javascript_include_tag "application"
= csrf_meta_tags

app/views/layouts/_site_footer.html.haml
.container.centre#share_btns
  .full_width
    %p Share this page on Facebook or Twitter:
    %p.small By clicking these buttons, you'll leave the GIZ website.

    =link_to I18n.t('buttons.url.facebook', share_url: page_og_url), target: '_blank', class: 'button iconbtn facebook' do
      =image_tag('icon-facebook-footer.svg')
      %span= I18n.t('buttons.facebook')

    =link_to I18n.t('buttons.url.twitter', share_url: page_og_url), target: '_blank', class: 'button iconbtn twitter' do
      =image_tag('icon-twitter-footer.svg')
      %span= I18n.t('buttons.twitter')

%footer{:class => "site-footer", :role => "contentinfo"}
  .container
    .third
      %ul
        %li=link_to 'Registration information', 'https://www.giz.de/en/html/registration_information.html', target: '_blank'
        %li=link_to "Terms and conditions", asset_path("giz_terms_conditions.pdf"), target: '_blank'
        %li=link_to "Data policy", asset_path("giz_data_processing.pdf"), target: '_blank'
        %li=link_to 'Legal information', legal_path
        %li.socials
          =link_to 'https://www.facebook.com/solutionchallenge', target: '_blank' do
            =image_tag('icon-facebook-footer.svg')
          =link_to 'https://www.twitter.com/solutionchallng', target: '_blank' do
            =image_tag('icon-twitter-footer.svg')
          =link_to 'https://www.youtube.com/user/GIZonlineTV', target: '_blank' do
            =image_tag('icon-youtube-footer.svg')
          =link_to 'https://www.linkedin.com/company/solutionchallenge/', target: '_blank' do
            =fa_icon 'linkedin'
          =link_to 'https://www.giz.de/de/mediathek/115.html', target: '_blank' do
            =image_tag('icon-rss-footer.svg')

app/views/layouts/_site_header.html.haml
.logo_bg

.container
  .logo
    =link_to 'https://www.giz.de/en', target: '_blank' do
      =image_tag('giz-logo.gif')
  .grey_section
    %h2=link_to t('strapline'), :root
    %nav
      = link_to t('buttons.overview'), :root, id: 'overview_nav'
      - if ApplicationState.instance.collection?
        - if current_user && current_user.solution&.id.present?
          = link_to t('buttons.edit_solution'), edit_solution_path(current_user.solution), id: 'submit_nav'
        - else
          = link_to t('buttons.submit_solution'), current_user ? :new_solution : :new_user_registration, id: 'submit_nav'
      = link_to t('buttons.browse_solution'), :solutions, id: 'browse_nav'
      - if current_user
        =link_to t('buttons.admin'), :edit_admin_application_state if admin_logged_in
        = button_to t('buttons.log_out'), :destroy_user_session, method: :delete, class: 'unstyle_button'
      -else
        = link_to t('buttons.log_in'), :new_user_session, id: 'log_in_nav'

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    = render 'layouts/html_head'

    %body{:class => page_class}
      %header{:class => "site-header", :role => "banner", id: "top_of_site"}
        = render 'layouts/site_header'
      = render 'layouts/alerts'
      %main{:class => "main", :id => "main", :role => "main"}
        = yield

      = render 'layouts/site_footer'

app/views/layouts/pdf.html.haml
%html{:lang => "en"}
  %head
    %meta{'http-equiv' => "content-type", :content =>"text/html", :charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title GIZ Call for Solutions
    %link{:href => "https://fonts.googleapis.com/css?family=Lato", :rel => "stylesheet", :type => "text/css"}

    %link{:href => "https://fonts.googleapis.com/css?family=Varela+Round", :rel => "stylesheet", :type => "text/css"}

    / = wicked_pdf_stylesheet_link_tag    "pdf-manifest"
    / = wicked_pdf_javascript_include_tag "pdf-manifest"

    :css
      #solution_show {
        display: block;
        clear: both;
        page-break-after: always;
      }

    %body.pdf
      .container
        = wicked_pdf_image_tag "giz-logo.gif", id: "logo"

      .wrapper
        = yield